// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0awSSauOVeoqMEfAd6MQBUY62UCJTnw4',
    appId: '1:984742026766:web:c08574c44058e16ee3e65f',
    messagingSenderId: '984742026766',
    projectId: 'new-project1-ababf',
    authDomain: 'new-project1-ababf.firebaseapp.com',
    storageBucket: 'new-project1-ababf.appspot.com',
    measurementId: 'G-CEJJG4CNTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc_df-NXvO8G0wLF6fyEq1fhzht7CLOPc',
    appId: '1:984742026766:android:d59b62f2ab8b3e6ce3e65f',
    messagingSenderId: '984742026766',
    projectId: 'new-project1-ababf',
    storageBucket: 'new-project1-ababf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7DYEv5sMdt-o_CGZUugYjXVej2Hp66M',
    appId: '1:984742026766:ios:d38242dbf6a4f2fce3e65f',
    messagingSenderId: '984742026766',
    projectId: 'new-project1-ababf',
    storageBucket: 'new-project1-ababf.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm7DYEv5sMdt-o_CGZUugYjXVej2Hp66M',
    appId: '1:984742026766:ios:d38242dbf6a4f2fce3e65f',
    messagingSenderId: '984742026766',
    projectId: 'new-project1-ababf',
    storageBucket: 'new-project1-ababf.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0awSSauOVeoqMEfAd6MQBUY62UCJTnw4',
    appId: '1:984742026766:web:fded0c0fd333a6dbe3e65f',
    messagingSenderId: '984742026766',
    projectId: 'new-project1-ababf',
    authDomain: 'new-project1-ababf.firebaseapp.com',
    storageBucket: 'new-project1-ababf.appspot.com',
    measurementId: 'G-MYDNMD947M',
  );
}
